item {
    id: 1
    name: 'actualizacionLogica_flecha'
}

item {
    id: 2
    name: 'archivoDefinitivo'
}

item {
    id: 3
    name: 'archivoTransitorio'
}

item {
    id: 4
    name: 'conector_comienzoCorte'
}

item {
    id: 5
    name: 'conector_reanudacionCorte'
}

item {
    id: 6
    name: 'consultaLogica_flecha'
}

item {
    id: 7
    name: 'control'
}

item {
    id: 8
    name: 'decision'
}

item {
    id: 9
    name: 'demora'
}

item {
    id: 10
    name: 'destruccion'
}

item {
    id: 11
    name: 'documento'
}

item {
    id: 12
    name: 'documentoElectronico'
}

item {
    id: 13
    name: 'operacion'
}

item {
    id: 14
    name: 'proceso'
}

item {
    id: 15
    name: 'procesoNoRelevado'
}

item {
    id: 16
    name: 'temporalidad'
}

item {
    id: 17
    name: 'trasladoDeInformacion_horizontal'
}

item {
    id: 18
    name: 'trasladoDeInformacion_vertical'
}